const { EMBED_COLORS, IMAGE } = require("@root/config");
const { getBuffer } = require("@helpers/HttpUtils");
const { cardStyle } = require("./RankingPolicy");

/**
 * The rank card is generated by Strange API (api.strangeapi.com), not drawn
 * locally - `barcolor` and `background` are its own parameter names. Both are
 * documented for the endpoint in general, but a server's own accent/background
 * have not been exercised against a live response yet, the same caveat as any
 * newly-wired external integration.
 *
 * @param {Object} input
 * @param {import('discord.js').User} input.user whose card this is
 * @param {number} input.level
 * @param {number} input.xp
 * @param {number} input.xpNeeded
 * @param {number} input.rank position on the leaderboard, 0 when unranked
 * @param {string} [input.presenceStatus]
 * @param {object} [input.settings] guild settings, for the server's own card style
 * @returns {string}
 */
function buildRankCardUrl({ user, level, xp, xpNeeded, rank, presenceStatus, settings }) {
  const style = cardStyle(settings);

  const url = new URL(`${IMAGE.BASE_API}/utils/rank-card`);
  url.searchParams.append("name", user.username);
  if (user.discriminator && user.discriminator !== "0") url.searchParams.append("discriminator", user.discriminator);
  url.searchParams.append("avatar", user.displayAvatarURL({ extension: "png", size: 128 }));
  url.searchParams.append("currentxp", String(xp));
  url.searchParams.append("reqxp", String(xpNeeded));
  url.searchParams.append("level", String(level));
  url.searchParams.append("barcolor", style.accent || EMBED_COLORS.BOT_EMBED);
  url.searchParams.append("status", presenceStatus || "idle");
  url.searchParams.append("rank", String(rank));
  if (style.background) url.searchParams.append("background", style.background);

  return url.href;
}

/**
 * @param {string} url from buildRankCardUrl
 * @returns {Promise<{success: boolean, buffer?: Buffer}>}
 */
function fetchRankCard(url) {
  return getBuffer(url, { headers: { Authorization: `Bearer ${process.env.STRANGE_API_KEY}` } });
}

module.exports = { buildRankCardUrl, fetchRankCard };
