module.exports = {
  automodHandler: require("./automod"),
  commandHandler: require("./command"),
  contextHandler: require("./context"),
  controlPanelHandler: require("./controlPanel"),
  counterHandler: require("./counter"),
  formHandler: require("./form"),
  greetingHandler: require("./greeting"),
  inviteHandler: require("./invite"),
  languageHandler: require("./language"),
  memberRoleHandler: require("./memberRoles"),
  modmailHandler: require("./modmail"),
  pollHandler: require("./polls"),
  presenceHandler: require("./presence"),
  reactionRoleHandler: require("./reactionRoles"),
  selfRoleHandler: require("./selfRoles"),
  starboardHandler: require("./starboard"),
  statsHandler: require("./stats"),
  stickyHandler: require("./stickyMessages"),
  suggestionHandler: require("./suggestion"),
  smartInvitesHandler: require("./smartInvites"),
  tempVoiceHandler: require("./tempVoice"),
  ticketHandler: require("./ticket"),
  translationHandler: require("./translation"),
  verificationHandler: require("./verification"),
  voiceRoleHandler: require("./voiceRoles"),
};
